# Generated by Django 4.2 on 2023-04-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeline", "0002_alter_phase_delay_alter_phase_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phase",
            name="delay",
            field=models.IntegerField(
                default=0, help_text="In weeks", verbose_name="Delay"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="duration",
            field=models.PositiveIntegerField(
                default=1, help_text="In weeks", verbose_name="Duration"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="phase_type",
            field=models.CharField(
                choices=[
                    ("#dddddd", "Other"),
                    ("#e3342f", "Feasibility study"),
                    ("#f6993f", "Preliminary design"),
                    ("#ffed4a", "Definitive design"),
                    ("#38c172", "Authoring"),
                    ("#4dc0b5", "Construction design"),
                    ("#3490dc", "Tender design"),
                    ("#6574cd", "Project management"),
                    ("#9561e2", "Construction supervision"),
                    ("#f66d9b", "Maintenance design"),
                ],
                default="#dddddd",
                max_length=7,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="start",
            field=models.DateField(blank=True, null=True, verbose_name="Start"),
        ),
    ]
